# permissions for end users to view imagevulnerabilities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagevulnerability-viewer-role
rules:
- apiGroups:
  - aquasecurity.github.io
  resources:
  - imagevulnerabilities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aquasecurity.github.io
  resources:
  - imagevulnerabilities/status
  verbs:
  - get
